### ISSUE TITLE
erro na execução do projeto

### ISSUE THREAD

**Issue by gilcleis** [alexsilva/b3irpf#1]
quando tento executar o projeto pela primeira vez seguindo as instruções do README.md acontece o seguinte erro:

```

Usuário (leave blank to use 'gil'): 
Endereço de email: gil@gil.com
Password: 
Password (again): 
Esta senha é muito curta. Ela precisa conter pelo menos 8 caracteres.
Esta senha é muito comum.
Esta senha é inteiramente numérica.
Bypass password validation and create user anyway? [y/N]: y
Superuser created successfully.
Traceback (most recent call last):
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: irpf_earnings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gil/Downloads/b3irpf/manage.py", line 22, in <module>
    main()
  File "/home/gil/Downloads/b3irpf/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/gil/Downloads/b3irpf/irpf/management/commands/setup_project.py", line 27, in handle
    call_command("setup_assets")
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/gil/Downloads/b3irpf/irpf/management/commands/setup_assets.py", line 23, in handle
    for instance in model.objects.filter(asset__isnull=True):
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: irpf_earnings
```

**Comment by alexsilva** [comment]
Executou os comandos?

python manage.py makemigrations
python manage.py migrate

**Comment by gilcleis** [comment]
sim executei os comandos:

```
python manage.py makemigrations
python manage.py migrate
python manage.py setup_project
```

**Comment by gilcleis** [comment]
no erro ta informando que não existe a tabela: irpf_earnings

`django.db.utils.OperationalError: no such table: irpf_earnings`

**Comment by alexsilva** [comment]
Essa falha é definido a falta dos pacotes de migração e foi corrigido.

Atualizar o projeto `cd b3irpf` e `git pull`

Reinstalar dependências (de preferência em um venv)
`pip install -r requirements.txt --force-reinstal`

Executar novamente
```
python manage.py makemigrations
python manage.py migrate
python manage.py setup_project
```
O projeto já funciona bem, até uso os relatórios para fazer minha declaração mas ainda contém falhas devido a poucos testes.
Mas se ainda estiver encontrando dificuldade me avise.

Meu testes são com os dados do site b3 investidor e corretora nuinvest (com as notas de corretagem).

**Comment by gilcleis** [comment]
os comandos

```
python manage.py makemigrations
python manage.py migrate
python manage.py setup_project
```
rodaram sem erro

agora quando rodo o 

`python manage.py runserver`

(.venv) gil@Matrix2:~/Downloads/b3irpf (master)$ python manage.py runserver
/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/assetprice/settings.py:8: UserWarning: App assetprice iniciando sem configuração de 'API_URL'...
  warnings.warn("App assetprice iniciando sem configuração de 'API_URL'...", UserWarning)
/home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/assetprice/settings.py:8: UserWarning: App assetprice iniciando sem configuração de 'API_URL'...
  warnings.warn("App assetprice iniciando sem configuração de 'API_URL'...", UserWarning)
Performing system checks...

System check identified no issues (0 silenced).
março 19, 2024 - 16:51:22
Django version 3.2.25, using settings 'b3irpf.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[19/Mar/2024 16:51:24] "GET / HTTP/1.1" 500 145
[19/Mar/2024 16:51:25] "GET /favicon.ico HTTP/1.1" 404 179
[19/Mar/2024 16:51:35] "GET / HTTP/1.1" 500 145
[19/Mar/2024 16:52:15] "GET / HTTP/1.1" 500 145
[19/Mar/2024 16:52:18] "GET / HTTP/1.1" 500 145
[19/Mar/2024 16:52:19] "GET /favicon.ico HTTP/1.1" 404 179

![image](https://github.com/alexsilva/b3irpf/assets/72532864/3f4b276d-7caa-4cd4-a12d-1182feb25750)



poderia colocar no projetor um arquivo irpf.env de exemplo 
ex.: example.env 
com as variáveis utilizada

**Comment by gilcleis** [comment]
esse API_URL seria o q?

**Comment by alexsilva** [comment]
> esse API_URL seria o q?

Isso é para url do status invest. Fiz um app separado para extrair dados do site e criar uma lista com a média dos dividendos pagos por ativo e definir um preço médio de compra usando os critérios de Décio Bazin.
Você pode ignorar isso configurando no arquivo env uma variável vazia.

`API_URL=""`

É uma implementação ainda inacabada.

No settings.py tem o mapeamento das variáveis que podem ser configuradas no arquivo env.

Depois vou incluir um arquivo env com as variáveis e explicações de cada opção, conforme sugerido.

**Comment by alexsilva** [comment]
> os comandos
> 
> ```
> python manage.py makemigrations
> python manage.py migrate
> python manage.py setup_project
> ```
> 
> rodaram sem erro
> 
> agora quando rodo o
> 
> `python manage.py runserver`
> 
> (.venv) gil@Matrix2:~/Downloads/b3irpf (master)$ python manage.py runserver /home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/assetprice/settings.py:8: UserWarning: App assetprice iniciando sem configuração de 'API_URL'... warnings.warn("App assetprice iniciando sem configuração de 'API_URL'...", UserWarning) /home/gil/Downloads/b3irpf/.venv/lib/python3.10/site-packages/assetprice/settings.py:8: UserWarning: App assetprice iniciando sem configuração de 'API_URL'... warnings.warn("App assetprice iniciando sem configuração de 'API_URL'...", UserWarning) Performing system checks...
> 
> System check identified no issues (0 silenced). março 19, 2024 - 16:51:22 Django version 3.2.25, using settings 'b3irpf.settings' Starting development server at http://127.0.0.1:8000/ Quit the server with CONTROL-C. [19/Mar/2024 16:51:24] "GET / HTTP/1.1" 500 145 [19/Mar/2024 16:51:25] "GET /favicon.ico HTTP/1.1" 404 179 [19/Mar/2024 16:51:35] "GET / HTTP/1.1" 500 145 [19/Mar/2024 16:52:15] "GET / HTTP/1.1" 500 145 [19/Mar/2024 16:52:18] "GET / HTTP/1.1" 500 145 [19/Mar/2024 16:52:19] "GET /favicon.ico HTTP/1.1" 404 179
> 
> ![image](https://private-user-images.githubusercontent.com/72532864/314153614-3f4b276d-7caa-4cd4-a12d-1182feb25750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjgzNDQsIm5iZiI6MTcxMDg2ODA0NCwicGF0aCI6Ii83MjUzMjg2NC8zMTQxNTM2MTQtM2Y0YjI3NmQtN2NhYS00Y2Q0LWExMmQtMTE4MmZlYjI1NzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE3MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OGQ0ZTdkODFkZmI5YWYzZGUzZDY3ZmY3MDQ5ODY2MTZlZjEzYjI1ZjQxZmM5M2ZiODAzOWU0NTI0NmVlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._d_jNhcERvnPnmXGU25ltNy36GzbTTTcLsr1Je7h6UA)
> 
> poderia colocar no projetor um arquivo irpf.env de exemplo ex.: example.env com as variáveis utilizada

Configura no .env a variável de debug

`DEBUG=ON`

**Comment by gilcleis** [comment]
agora rodou 

![image](https://github.com/alexsilva/b3irpf/assets/72532864/e9c0033b-0ad3-457c-8c54-cfef3c9b29e1)

muito obrigado já pode fecha essa issues
